services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/hospitaliq
      dockerfile: Dockerfile
    volumes:
      - ./frontend/hospitaliq:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - BACKEND_URL=${BACKEND_URL}
    env_file:
      - .env
